development:
  adapter: mysql2
  encoding: utf8
  database: seu-remedio-v2_development
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
  
test:
  adapter: mysql2
  encoding: utf8
  database: seu-remedio-v2_test
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: seu-remedio-v2_production
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
